# This workflow  performs an install of the latest packages of all dependecies(feature/tests branch) and executes tests
name: Nightly Test

on:
# This can be used to automatically publish nightlies at UTC nighttime
  schedule:
    - cron: '0 23 * * *' # run at 11 PM UTC
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:
jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install && npm update
      - run: cd tests && npm install && npm update
      - run: npm run test
      - run: npm list
      - run: cd tests && npm list
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: feature/tests
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: npm install && npm update
      - run: cd tests && npm install && npm update
      - run: npm run test
      - run: npm list
      - run: cd tests && npm list

